### PR TITLE
League Statistics Refactor and CSV changes

### PR DESCRIPTION
**Pull request by ethanb1145**
## Description

Refactored the LeagueStatistics file to the universal way that we are reading CSV files. Refactored the methods to go off of the CSV files that are in the initialize of the class. Refactored the spec files to do so as well. Added a helper method to help with the 'best_offense' method by finding the name of a team by the id.

Made changes to the way the CSV is read. Made additional fixes for tests to pass. 

## Type of change

- [x] fix
- [x] feat
- [x] test
- [x] refactor
- [ ] docs

## Checklist

- [x] code has been self reviewed
- [x] code runs without any errors
- [x] thorough testing has been implemented if adding feature
- [x] all tests pass

### Thanks!

### CODE REVIEW

**Comment by elizakeating** [comment]
Nice helper method! Looks good! Thanks for fixing the season_statistics to our CSV.read change!

**Comment by elizakeating** [comment]
Thanks for changing the season_statistic files for our .read change! The league methods look good!

**Comment by kbug819** [comment]
Great job with the methods, and thank you for making all the .reach changes!

**Review by nurudeensulaimon — COMMENTED** [review]
Great job on refactoring the  league statistics

**Pull request merged**
